# -*- mode: ruby -*-
# vi: set ft=ruby

Vagrant.require_version ">= 2.3.0"
VAGRANTFILE_API_VERSION = "2"

require "yaml"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.synced_folder '.', '/vagrant', disabled: true

    config.vm.boot_timeout = 600
    config.vm.graceful_halt_timeout = 600
    config.winrm.retry_limit = 30
    config.winrm.retry_delay = 10

    # Domain Controllers
    hosts_path_dc = "../ansible/host_vars/dc*/*.yml"
    hosts_filename_dc = Dir.glob(hosts_path_dc)

    hosts_filename_dc.each do |host_filename_dc|
        domain_controller = YAML.load_file(File.join(File.dirname(__FILE__), host_filename_dc))

        host_name   = domain_controller["host_name"]
        host_ip     = domain_controller["host_ip"]
        vagrant_box = domain_controller["vagrant_box"]
        vm_name     = domain_controller["vm_name"]
        vm_gui      = domain_controller["vm_gui"]
        vm_memory   = domain_controller["vm_memory"]
        vm_cpus     = domain_controller["vm_cpus"]
        vm_os       = domain_controller["operating_system"]

        config.vm.define host_name do |dc|
            dc.vm.hostname      = host_name
            dc.vm.box           = vagrant_box
            dc.vm.network :private_network, ip: host_ip, vmnet_id: "vmnet8"

            if vm_os == "windows" then
                dc.vm.guest = :windows
                dc.vm.communicator = "winrm"
                dc.vm.provision :shell, inline: "netsh advfirewall set allprofiles state off", privileged: true
                dc.vm.provision :shell, :path => "./script/Install-WMF3Hotfix.ps1", privileged: false
                dc.vm.provision :shell, :path => "./script/ConfigureRemotingForAnsible.ps1", privileged: false
            end

            dc.vm.provider "vmware_desktop" do |vmware|
                vmware.vmx["displayname"]  = "breakingbAD_" + vm_name
                vmware.gui                 = vm_gui
                vmware.vmx["memsize"]      = vm_memory.to_s
                vmware.vmx["numvcpus"]     = vm_cpus.to_s
                vmware.linked_clone        = true
                vmware.allowlist_verified  = true
            end
        end
    end

    # Servers
    hosts_path_srv = "../ansible/host_vars/srv*/*.yml"
    hosts_filename_srv = Dir.glob(hosts_path_srv)

    hosts_filename_srv.each do |host_filename_srv|
        server = YAML.load_file(File.join(File.dirname(__FILE__), host_filename_srv))

        host_name   = server["host_name"]
        host_ip     = server["host_ip"]
        vagrant_box = server["vagrant_box"]
        vm_name     = server["vm_name"]
        vm_gui      = server["vm_gui"]
        vm_memory   = server["vm_memory"]
        vm_cpus     = server["vm_cpus"]
        vm_os       = server["operating_system"]

        config.vm.define host_name do |srv|
            srv.vm.hostname     = host_name
            srv.vm.box          = vagrant_box
            srv.vm.network :private_network, ip: host_ip, vmnet_id: "vmnet8"

            if vm_os == "windows" then
                srv.vm.guest = :windows
                srv.vm.communicator = "winrm"
                srv.vm.provision :shell, inline: "netsh advfirewall set allprofiles state off", privileged: true
                srv.vm.provision :shell, :path => "script/Install-WMF3Hotfix.ps1", privileged: false
                srv.vm.provision :shell, :path => "script/ConfigureRemotingForAnsible.ps1", privileged: false
            end

            srv.vm.provider "vmware_desktop" do |vmware|
                vmware.vmx["displayname"]  = "breakingbAD_" + vm_name
                vmware.gui                 = vm_gui
                vmware.vmx["memsize"]      = vm_memory.to_s
                vmware.vmx["numvcpus"]     = vm_cpus.to_s
                vmware.linked_clone        = true
                vmware.allowlist_verified  = true
            end
        end
    end
end
